version: '3.4'
services:
  php:
    build: ./php-fpm
    volumes:
      - ././silex_api:/usr/src/silex/app
  nginx:
    image: nginx
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ././silex_api:/usr/src/silex/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf